# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [2]:
import numpy as np
import pandas as pd

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [5]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame({
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
})

    Name  Age         City
0   John   16     New York
1  Emily   28  Los Angeles
2   Ryan   22      Chicago

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [13]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [15]:
df["Salary"] = [50000, 60000, 70000]
df

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   70000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [17]:
df[df["Age"] > 18]

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   70000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [22]:
current_year = 2025
birth_year = current_year - df["Age"]
df["Birth year"] = birth_year
df

    Name  Age         City  Salary  Birth year
0   John   16     New York   50000        2009
1  Emily   28  Los Angeles   60000        1997
2   Ryan   22      Chicago   70000        2003

### Task 4.2

Add new calculated field `Average age`.

In [31]:
df["Average age"] = df["Age"].sum() / len(df["Age"]) 
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2009         22.0
1  Emily   28  Los Angeles   60000        1997         22.0
2   Ryan   22      Chicago   70000        2003         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [34]:
df["Absolute difference"] = df["Age"] - df["Average age"]
df

,Name,Age,City,Salary,Birth year,Average age,Absolute difference
0,John,16,New York,50000,2009,22.0,-6.0
1,Emily,28,Los Angeles,60000,1997,22.0,6.0
2,Ryan,22,Chicago,70000,2003,22.0,0.0

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [32]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(
    {'Name': 
         ['John', 'Emily', 'Ryan'],
     'Age': [25, 28, 22]
     })
df2 = pd.DataFrame(
    {'Name': 
         ['Emily', 'Ryan', 'Mike'],
     'City': ['Los Angeles', 'Chicago', 'Houston']
     })
display(df1, df2)

    Name  Age
0   John   25
1  Emily   28
2   Ryan   22

    Name         City
0  Emily  Los Angeles
1   Ryan      Chicago
2   Mike      Houston

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0  Los Angeles
2   Ryan  22.0      Chicago
3   Mike   NaN      Houston

In [34]:
display(pd.merge(df1, df2, how='outer'))

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0  Los Angeles
2   Ryan  22.0      Chicago
3   Mike   NaN      Houston

In [33]:
display(pd.concat([df1, df2], ignore_index=True))

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
3  Emily   NaN  Los Angeles
4   Ryan   NaN      Chicago
5   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [36]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [44]:
series3 = s1 + s2
series3

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [45]:
series3 = s1 - s2
series3

0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64

In [46]:
series3 = s1 * s2
series3

0     6
1    14
2    24
3    36
4    50
dtype: int64

In [47]:
series3 = s1 / s2
series3

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64

In [48]:
series3 = s1 ** s2
series3

0          1
1        128
2       6561
3     262144
4    9765625
dtype: int64

In [50]:
series3 = s2 // s1
series3

0    6
1    3
2    2
3    2
4    2
dtype: int64

In [51]:
series3 = s2 % s1
series3

0    0
1    1
2    2
3    1
4    0
dtype: int64

In [56]:
filtered_s1 = s1[s1 % 2 == 0]
filtered_s1

1    2
3    4
dtype: int64

In [57]:
filtered_s2 = s2[s2 % 2 == 1]
filtered_s2

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [60]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [65]:
s.str.upper()

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [66]:
s.str.len()

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [67]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: total: 15.7 s
Wall time: 15.9 s

[58.4, 58.8, 54.6, 65.2, 73.0, 73.2, 66.6, 68.4, 52.6, 44.2]

### Solution using Pandas and Numpy

In [88]:
df = pd.DataFrame(data, columns=['random_numbers'])
df['SMA'] = df['random_numbers'].rolling(window=5).mean() 
%timeit df['SMA'].dropna()

151 ms ± 37.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)